# Generated by Django 5.2.6 on 2026-04-01 22:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastro', '0019_cliente_comprovante_nome_cliente_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('acoes', 'Em andamento'), ('finalizado', 'Finalizado'), ('assinado', 'Assinado')], default='rascunho', max_length=15)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kits', to='cadastro.cliente')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kits_criados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoKit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('contrato', 'Contrato de Prestação de Serviços'), ('procuracao', 'Procuração'), ('hipossuficiencia', 'Declaração de Hipossuficiência'), ('ciencia', 'Declaração de Ciência'), ('domicilio', 'Declaração de Domicílio')], max_length=20)),
                ('arquivo', models.FileField(upload_to='kits/documentos/')),
                ('gerado_em', models.DateTimeField(auto_now_add=True)),
                ('kit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='kits.kit')),
            ],
            options={
                'verbose_name': 'Documento do Kit',
                'verbose_name_plural': 'Documentos do Kit',
                'ordering': ['tipo'],
            },
        ),
        migrations.CreateModel(
            name='AcaoKit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_acao', models.CharField(choices=[('cartao_credito_consignado', 'Cartão de Crédito Consignado'), ('rmc', 'RMC'), ('rcc', 'RCC'), ('emprestimo_nao_autorizado', 'Empréstimo Não Autorizado'), ('tarifa_bancaria', 'Tarifa Bancária'), ('contribuicao_sindical_nao_autorizada', 'Contribuição Sindical Não Autorizada'), ('seguro_nao_autorizado', 'Seguro Não Autorizado')], max_length=50)),
                ('nome_banco', models.CharField(max_length=100)),
                ('banco_outro', models.CharField(blank=True, max_length=100)),
                ('numero_contrato', models.CharField(blank=True, max_length=50)),
                ('tarifa_questionada', models.CharField(blank=True, max_length=100)),
                ('tipo_seguro', models.TextField(blank=True)),
                ('tipo_contribuicao', models.TextField(blank=True)),
                ('historico_emprestimo', models.FileField(blank=True, upload_to='kits/acoes/')),
                ('historico_credito', models.FileField(blank=True, upload_to='kits/acoes/')),
                ('extrato_bancario', models.FileField(blank=True, upload_to='kits/acoes/')),
                ('kit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acoes', to='kits.kit')),
            ],
            options={
                'verbose_name': 'Ação do Kit',
                'verbose_name_plural': 'Ações do Kit',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='kit',
            index=models.Index(fields=['criado_por', '-criado_em'], name='kits_kit_criado__1c1dcd_idx'),
        ),
        migrations.AddIndex(
            model_name='kit',
            index=models.Index(fields=['cliente', '-criado_em'], name='kits_kit_cliente_4b4aed_idx'),
        ),
        migrations.AddIndex(
            model_name='kit',
            index=models.Index(fields=['status'], name='kits_kit_status_fb4a3d_idx'),
        ),
    ]
