# Generated by Codex on 2026-04-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kits", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="acaokit",
            name="extrato_bancario_arquivos",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="acaokit",
            name="historico_credito_arquivos",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="acaokit",
            name="historico_emprestimo_arquivos",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
