# Generated by Django 5.2.6 on 2026-04-18 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kits', '0004_alter_acaokit_numero_contrato'),
    ]

    operations = [
        migrations.AddField(
            model_name='kit',
            name='tipo',
            field=models.CharField(choices=[('bancario', 'Bancário'), ('previdenciario', 'Previdenciário')], default='bancario', max_length=20),
        ),
    ]
