# Generated by Django 5.2.6 on 2026-04-23 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kits', '0005_add_tipo_to_kit'),
    ]

    operations = [
        migrations.CreateModel(
            name='BancoKit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('ativo', models.BooleanField(default=True)),
                ('ordem', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Banco',
                'verbose_name_plural': 'Bancos',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='TarifaKit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, unique=True)),
                ('ativo', models.BooleanField(default=True)),
                ('ordem', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Tarifa',
                'verbose_name_plural': 'Tarifas',
                'ordering': ['ordem', 'nome'],
            },
        ),
    ]
