# Generated by Django 5.2.6 on 2026-04-23 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kits', '0006_add_banco_tarifa_kit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acaokit',
            name='nome_banco',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
