# Generated by Django 5.2.6 on 2026-05-07 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kits', '0007_banco_not_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kit',
            name='tipo',
            field=models.CharField(choices=[('bancario', 'Bancário'), ('previdenciario', 'Previdenciário'), ('marketing', 'Marketing')], default='bancario', max_length=20),
        ),
    ]
