# Generated by Django 5.2.6 on 2026-05-11 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kits', '0008_alter_kit_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssociacaoKit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, unique=True)),
                ('abreviacao', models.CharField(blank=True, max_length=30)),
                ('ativo', models.BooleanField(default=True)),
                ('ordem', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Associação',
                'verbose_name_plural': 'Associações',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.AddField(
            model_name='acaokit',
            name='associacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acoes', to='kits.associacaokit'),
        ),
    ]
