# Generated by Django 5.2.6 on 2026-06-03 12:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kits', '0009_associacaokit_acaokit_associacao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='kit',
            name='clausula_porcentagem_snapshot',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='ClausulaPorcentagemPadrao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(blank=True, default='')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cláusula de porcentagem — padrão',
                'verbose_name_plural': 'Cláusula de porcentagem — padrão',
            },
        ),
        migrations.CreateModel(
            name='ClausulaPorcentagemUF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uf', models.CharField(max_length=2, unique=True)),
                ('texto', models.TextField()),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cláusula de porcentagem — variação por UF',
                'verbose_name_plural': 'Cláusula de porcentagem — variações por UF',
                'ordering': ['uf'],
            },
        ),
    ]
