# Generated by Django 5.2.6 on 2026-06-03 12:01

from django.db import migrations


def create_singleton(apps, schema_editor):
    ClausulaPorcentagemPadrao = apps.get_model("kits", "ClausulaPorcentagemPadrao")
    ClausulaPorcentagemPadrao.objects.get_or_create(pk=1, defaults={"texto": ""})


def noop_reverse(apps, schema_editor):
    # Singleton é seguro deixar — não apagamos no rollback.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('kits', '0010_kit_clausula_porcentagem_snapshot_and_more'),
    ]

    operations = [
        migrations.RunPython(create_singleton, noop_reverse),
    ]
