# Generated by Django 5.2.6 on 2026-06-03 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kits', '0011_seed_clausula_porcentagem_padrao'),
    ]

    operations = [
        migrations.AddField(
            model_name='kit',
            name='advogados_snapshot',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
