# Generated by Django 5.2.6 on 2026-06-03 15:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kits', '0012_kit_advogados_snapshot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clausulaporcentagemuf',
            options={'ordering': ['uf', 'tipo_acao'], 'verbose_name': 'Cláusula de porcentagem — variação por UF', 'verbose_name_plural': 'Cláusula de porcentagem — variações por UF'},
        ),
        migrations.AddField(
            model_name='clausulaporcentagemuf',
            name='tipo_acao',
            field=models.CharField(blank=True, default='', help_text='Tipo de ação ao qual a variação se aplica. Vazio = variação genérica para qualquer ação naquela UF.', max_length=50),
        ),
        migrations.AlterField(
            model_name='clausulaporcentagemuf',
            name='uf',
            field=models.CharField(max_length=2),
        ),
        migrations.AddConstraint(
            model_name='clausulaporcentagemuf',
            constraint=models.UniqueConstraint(fields=('uf', 'tipo_acao'), name='unique_clausula_uf_tipo'),
        ),
    ]
