# Generated by Django 5.2.6 on 2026-07-17 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kits', '0014_kit_app_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='kit',
            name='notificacao_enviada',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='kit',
            name='notificacao_enviada_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
