# Generated by Django 5.2.6 on 2026-07-17 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kits', '0015_kit_notificacao_enviada_kit_notificacao_enviada_em'),
    ]

    operations = [
        migrations.AddField(
            model_name='bancokit',
            name='cnpj',
            field=models.CharField(blank=True, default='', max_length=18),
        ),
        migrations.AddField(
            model_name='bancokit',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='bancokit',
            name='endereco',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
