# Generated by Django 5.2.6 on 2026-07-17 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kits', '0016_bancokit_cnpj_bancokit_email_bancokit_endereco'),
        ('kits', '0016_documentokit_zapsign_fields'),
    ]

    operations = [
    ]
