# Generated by Django 5.2.6 on 2026-07-24 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kits', '0017_merge_20260717_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='kit',
            name='honorarios_iniciais',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
