# Generated by Django 5.2.6 on 2026-09-02 13:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0030_contaclienteapp_telefone_and_more'),
        ('kits', '0019_kit_zapsign_portal_token'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='kit',
            name='baixado_em',
            field=models.DateTimeField(blank=True, help_text='Quando a aplicação externa baixou o kit da esteira.', null=True),
        ),
        migrations.AddField(
            model_name='kit',
            name='entrou_esteira_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kit',
            name='status_esteira',
            field=models.CharField(choices=[('aguardando', 'Aguardando esteira'), ('na_esteira', 'Na esteira'), ('concluido', 'Concluído')], db_index=True, default='aguardando', max_length=12),
        ),
        migrations.AddField(
            model_name='kit',
            name='via_assinatura',
            field=models.CharField(blank=True, choices=[('zapsign', 'Digital (ZapSign)'), ('presencial', 'Presencial')], default='', help_text='Via escolhida na etapa final: assinatura pelo ZapSign ou presencial.', max_length=12),
        ),
        migrations.AlterField(
            model_name='documentokit',
            name='tipo',
            field=models.CharField(choices=[('contrato', 'Contrato de Prestação de Serviços'), ('procuracao', 'Procuração'), ('hipossuficiencia', 'Declaração de Hipossuficiência'), ('ciencia', 'Declaração de Ciência'), ('domicilio', 'Declaração de Domicílio'), ('assinado_zapsign', 'Kit Assinado (ZapSign)'), ('assinado_presencial', 'Kit Assinado (Presencial)')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='kit',
            index=models.Index(fields=['status_esteira', '-entrou_esteira_em'], name='kits_kit_status__9bba9c_idx'),
        ),
    ]
