# Generated by Django 5.2.6 on 2026-09-04 02:06

from django.db import migrations, models


def reclassificar_aguardando(apps, schema_editor):
    """Os dois status antigos mudaram de significado; os registros vão junto.

    Antes:  aguardando = padrão de qualquer kit (assinado ou não)
            na_esteira = kit assinado e disponível
    Agora:  em_producao = kit ainda sendo montado
            aguardando  = assinado e disponível para a aplicação externa assumir
            na_esteira  = a aplicação externa ASSUMIU e está processando

    Duas correções, portanto:

    1. `aguardando` antigo → `em_producao`. Inclui kits já assinados, de
       propósito: mantém a decisão de não despejar o histórico do escritório na
       fila da aplicação externa. Kits antigos que devam entrar são promovidos
       caso a caso.

    2. `na_esteira` sem `assumido_em` → `aguardando`. São os kits assinados
       enquanto `na_esteira` ainda significava "disponível"; deixá-los como estão
       diria que a aplicação externa os assumiu, o que nunca aconteceu. A data de
       disponibilização (`entrou_esteira_em`) desses é legítima e fica.
    """
    Kit = apps.get_model('kits', 'Kit')

    Kit.objects.filter(status_esteira='aguardando').update(
        status_esteira='em_producao',
        entrou_esteira_em=None,
    )
    Kit.objects.filter(status_esteira='na_esteira', assumido_em__isnull=True).update(
        status_esteira='aguardando',
    )


def desfazer_reclassificacao(apps, schema_editor):
    """Volta ao padrão anterior, em que todo kit nascia `aguardando`."""
    Kit = apps.get_model('kits', 'Kit')
    Kit.objects.filter(status_esteira='em_producao').update(status_esteira='aguardando')


class Migration(migrations.Migration):

    dependencies = [
        ('kits', '0020_kit_baixado_em_kit_entrou_esteira_em_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kit',
            name='assumido_em',
            field=models.DateTimeField(blank=True, help_text='Quando a aplicação externa assumiu o kit e começou a processá-lo.', null=True),
        ),
        migrations.AlterField(
            model_name='kit',
            name='entrou_esteira_em',
            field=models.DateTimeField(blank=True, help_text='Quando o kit foi assinado e ficou disponível para a aplicação externa.', null=True),
        ),
        migrations.AlterField(
            model_name='kit',
            name='status_esteira',
            field=models.CharField(choices=[('em_producao', 'Em produção'), ('aguardando', 'Aguardando esteira'), ('na_esteira', 'Na esteira'), ('concluido', 'Concluído')], db_index=True, default='em_producao', max_length=12),
        ),
        migrations.RunPython(reclassificar_aguardando, desfazer_reclassificacao),
    ]
