# Generated by Django 5.2.5 on 2025-10-31 17:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastro', '0006_cliente_estado_civil_cliente_nacionalidade_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_contrato', models.CharField(db_index=True, max_length=50)),
                ('banco_nome', models.CharField(max_length=120, verbose_name='Banco')),
                ('banco_id', models.CharField(blank=True, help_text='COMPE/ISPB ou identificador interno', max_length=32, verbose_name='Código do banco')),
                ('situacao', models.CharField(blank=True, choices=[('ativo', 'Ativo'), ('suspenso', 'Suspenso'), ('baixado', 'Baixado'), ('encerrado', 'Encerrado')], max_length=20)),
                ('origem_averbacao', models.CharField(blank=True, choices=[('consignado', 'Consignado'), ('cartao', 'Cartão consignado'), ('refin', 'Refinanciamento'), ('portabilidade', 'Portabilidade'), ('outros', 'Outros')], max_length=30)),
                ('data_inclusao', models.DateField(blank=True, null=True)),
                ('data_inicio_desconto', models.DateField(blank=True, null=True)),
                ('data_fim_desconto', models.DateField(blank=True, null=True)),
                ('quantidade_parcelas', models.PositiveIntegerField(blank=True, null=True)),
                ('valor_parcela', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('iof', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='IOF')),
                ('valor_emprestado', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Emprestado')),
                ('valor_liberado', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Liberado')),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos', to='cadastro.cliente')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contratos_criados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
                'ordering': ['-criado_em', 'cliente', 'numero_contrato'],
                'indexes': [models.Index(fields=['cliente', 'numero_contrato'], name='contracts_c_cliente_267912_idx')],
            },
        ),
    ]
