# Generated by Django 5.2.5 on 2025-10-31 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='origem_averbacao',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Origem da Averbação'),
        ),
    ]
