# Generated by Django 5.2.5 on 2025-10-31 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_alter_contrato_origem_averbacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='origem_averbacao',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Origem da Averbação'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='situacao',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Situação'),
        ),
    ]
