# Generated by Django 5.2.6 on 2026-03-15 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0017_alter_contrato_cliente'),
        ('contracts', '0004_contrato_cliente_data_inclusao_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos_contracts', to='cadastro.cliente'),
        ),
    ]
