# Generated by Django 5.2.5 on 2025-09-08 00:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_contabancaria_unique_principal_per_cliente'),
        ('petitions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='petition',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='petitions', to='cadastro.cliente'),
        ),
        migrations.AddField(
            model_name='petition',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='petition',
            name='context',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='petition',
            name='output',
            field=models.FileField(blank=True, null=True, upload_to='petitions/'),
        ),
    ]
