# Generated by Django 5.2.5 on 2025-09-08 00:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_contabancaria_unique_principal_per_cliente'),
        ('petitions', '0002_petition_cliente_petition_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petition',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='petitions', to='cadastro.cliente'),
        ),
    ]
