# Generated by Django 5.2.5 on 2025-09-20 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petitions', '0003_alter_petition_cliente'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='petition',
            options={'ordering': ['-created_at']},
        ),
    ]
