# Generated by Django 5.2.6 on 2026-05-22 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_extras_e_permissao"),
    ]

    operations = [
        migrations.CreateModel(
            name="AppClient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "client_id",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                ("client_secret_hash", models.CharField(max_length=256)),
                (
                    "nome",
                    models.CharField(
                        help_text="Nome identificador da aplicação cliente (ex.: Backend App Colaboradores)",
                        max_length=120,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "App Client",
                "verbose_name_plural": "App Clients",
                "ordering": ["nome"],
            },
        ),
    ]
