# Generated by Django 5.2.6 on 2026-07-24 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_create_app_flowalr_user'),
        ('permissoes', '0002_seed_capacidades'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='capacidades_diretas',
            field=models.ManyToManyField(blank=True, related_name='usuarios_diretos', to='permissoes.capacidade'),
        ),
    ]
