# Generated by Django 5.2.6 on 2026-08-07 01:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_user_capacidades_diretas"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="acesso_app",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Permite login no app FlowALR com as credenciais do JurisDoc.",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="acesso_app_liberado_em",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="acesso_app_liberado_por",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="acessos_app_concedidos",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
