# Generated by Django 5.2.5 on 2025-08-13 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('file', models.FileField(upload_to='templates/')),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
