# Generated by Django 5.2.5 on 2025-08-15 01:26

import cadastro.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(db_index=True, max_length=200)),
                ('cpf', models.CharField(max_length=11, unique=True, validators=[cadastro.validators.validate_cpf])),
                ('rg', models.CharField(blank=True, max_length=20)),
                ('orgao_expedidor', models.CharField(blank=True, max_length=20)),
                ('qualificacao', models.TextField(blank=True)),
                ('se_idoso', models.BooleanField(default=False)),
                ('logradouro', models.CharField(blank=True, max_length=120)),
                ('numero', models.CharField(blank=True, max_length=20)),
                ('bairro', models.CharField(blank=True, max_length=120)),
                ('cidade', models.CharField(blank=True, max_length=120)),
                ('cep', models.CharField(blank=True, max_length=8, validators=[cadastro.validators.validate_cep])),
                ('uf', models.CharField(blank=True, max_length=2, validators=[cadastro.validators.validate_uf])),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['nome_completo'],
            },
        ),
        migrations.CreateModel(
            name='ContaBancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banco_nome', models.CharField(max_length=100)),
                ('banco_codigo', models.CharField(blank=True, max_length=5)),
                ('agencia', models.CharField(max_length=10)),
                ('conta', models.CharField(max_length=20)),
                ('digito', models.CharField(blank=True, max_length=5)),
                ('tipo', models.CharField(choices=[('corrente', 'Corrente'), ('poupanca', 'Poupança'), ('salario', 'Salário')], default='corrente', max_length=10)),
                ('is_principal', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contas', to='cadastro.cliente')),
            ],
            options={
                'ordering': ['cliente', 'banco_nome', 'agencia', 'conta'],
                'unique_together': {('cliente', 'banco_nome', 'agencia', 'conta', 'digito')},
            },
        ),
    ]
