# Generated by Django 5.2.5 on 2025-08-15 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='contabancaria',
            constraint=models.UniqueConstraint(condition=models.Q(('is_principal', True)), fields=('cliente',), name='unique_principal_per_cliente'),
        ),
    ]
