# Generated by Django 5.2.5 on 2025-09-15 19:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_contabancaria_unique_principal_per_cliente'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DescricaoBanco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banco_id', models.CharField(db_index=True, max_length=32, unique=True)),
                ('banco_nome', models.CharField(max_length=120)),
                ('descricao', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='descricoes_banco_editadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Descrição de Banco',
                'verbose_name_plural': 'Descrições de Banco',
                'ordering': ['banco_nome'],
            },
        ),
    ]
