# Generated by Django 5.2.5 on 2025-09-15 21:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0003_descricaobanco'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='descricaobanco',
            options={'ordering': ['banco_nome', '-is_ativa', '-atualizado_em'], 'verbose_name': 'Descrição de Banco', 'verbose_name_plural': 'Descrições de Banco'},
        ),
        migrations.AddField(
            model_name='descricaobanco',
            name='is_ativa',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='descricaobanco',
            name='banco_id',
            field=models.CharField(db_index=True, max_length=32),
        ),
        migrations.AddIndex(
            model_name='descricaobanco',
            index=models.Index(fields=['banco_id', 'atualizado_em'], name='cadastro_de_banco_i_3ccc6b_idx'),
        ),
        migrations.AddConstraint(
            model_name='descricaobanco',
            constraint=models.UniqueConstraint(condition=models.Q(('is_ativa', True)), fields=('banco_id',), name='unique_active_descricaobanco_per_bank'),
        ),
    ]
