# Generated by Django 5.2.5 on 2025-09-20 22:43

import cadastro.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0005_drop_unique_banco_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='estado_civil',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='cliente',
            name='nacionalidade',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='cliente',
            name='profissao',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='cliente',
            name='se_crianca_adolescente',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cliente',
            name='se_incapaz',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Representante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(db_index=True, max_length=200)),
                ('cpf', models.CharField(max_length=11, validators=[cadastro.validators.validate_cpf])),
                ('rg', models.CharField(blank=True, max_length=20)),
                ('orgao_expedidor', models.CharField(blank=True, max_length=20)),
                ('se_idoso', models.BooleanField(default=False)),
                ('se_incapaz', models.BooleanField(default=False)),
                ('se_crianca_adolescente', models.BooleanField(default=False)),
                ('nacionalidade', models.CharField(blank=True, max_length=60)),
                ('estado_civil', models.CharField(blank=True, max_length=20)),
                ('profissao', models.CharField(blank=True, max_length=120)),
                ('usa_endereco_do_cliente', models.BooleanField(default=False)),
                ('logradouro', models.CharField(blank=True, max_length=120)),
                ('numero', models.CharField(blank=True, max_length=20)),
                ('bairro', models.CharField(blank=True, max_length=120)),
                ('cidade', models.CharField(blank=True, max_length=120)),
                ('cep', models.CharField(blank=True, max_length=8, validators=[cadastro.validators.validate_cep])),
                ('uf', models.CharField(blank=True, max_length=2, validators=[cadastro.validators.validate_uf])),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='representantes', to='cadastro.cliente')),
            ],
            options={
                'ordering': ['cliente', 'nome_completo'],
                'indexes': [models.Index(fields=['cliente', 'nome_completo'], name='cadastro_re_cliente_a67611_idx')],
                'constraints': [models.UniqueConstraint(fields=('cliente', 'cpf'), name='unique_representante_por_cliente')],
            },
        ),
    ]
