# Generated by Django 5.2.5 on 2025-11-06 19:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0006_cliente_estado_civil_cliente_nacionalidade_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='descricaobanco',
            options={'ordering': ['banco_nome', '-is_ativa', '-atualizado_em'], 'verbose_name': 'Descrição de Banco', 'verbose_name_plural': 'Descrições de Bancos'},
        ),
        migrations.RemoveConstraint(
            model_name='descricaobanco',
            name='unique_active_descricaobanco_per_bank',
        ),
        migrations.RemoveIndex(
            model_name='descricaobanco',
            name='cadastro_de_banco_i_3ccc6b_idx',
        ),
        migrations.RemoveField(
            model_name='descricaobanco',
            name='descricao',
        ),
        migrations.AddField(
            model_name='descricaobanco',
            name='cnpj',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
        migrations.AddField(
            model_name='descricaobanco',
            name='endereco',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='descricaobanco',
            name='nome_banco',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='descricaobanco',
            name='atualizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='descricoes_banco_atualizadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='descricaobanco',
            name='banco_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='descricaobanco',
            name='banco_nome',
            field=models.CharField(max_length=255),
        ),
    ]
