# Generated by Django 5.2.6 on 2025-12-12 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0006_cliente_estado_civil_cliente_nacionalidade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
