# Generated by Django 5.2.6 on 2025-12-13 00:02

import cadastro.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0007_cliente_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContaBancariaReu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banco_nome', models.CharField(max_length=100)),
                ('banco_codigo', models.CharField(blank=True, max_length=5)),
                ('cnpj', models.CharField(max_length=14, validators=[cadastro.validators.validate_cnpj])),
                ('logradouro', models.CharField(blank=True, max_length=120)),
                ('numero', models.CharField(blank=True, max_length=20)),
                ('bairro', models.CharField(blank=True, max_length=120)),
                ('cidade', models.CharField(blank=True, max_length=120)),
                ('estado', models.CharField(blank=True, max_length=2, validators=[cadastro.validators.validate_uf])),
                ('cep', models.CharField(blank=True, max_length=8, validators=[cadastro.validators.validate_cep])),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contas_reu', to='cadastro.cliente')),
            ],
            options={
                'verbose_name': 'Banco do Réu',
                'verbose_name_plural': 'Bancos dos Réus',
                'ordering': ['cliente', 'banco_nome'],
                'unique_together': {('cliente', 'banco_nome', 'cnpj')},
            },
        ),
    ]
