# Generated by Django 5.2.6 on 2025-12-13 02:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0008_contabancariareu'),
        ('templates_app', '0002_alter_template_options_template_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contratos', models.JSONField(blank=True, default=list, help_text='Array JSONB com os dados de cada contrato')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='cadastro.cliente')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='templates_app.template')),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
                'ordering': ['-criado_em'],
            },
        ),
    ]
