# Generated by Django 5.2.6 on 2025-12-13 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0009_contrato'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='imagem_do_contrato',
            field=models.ImageField(blank=True, help_text='Imagem do contrato', null=True, upload_to='contratos/'),
        ),
    ]
