# Generated by Django 5.2.6 on 2025-12-16 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0010_contrato_imagem_do_contrato'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='verifica_documento',
            field=models.JSONField(blank=True, default=dict, help_text='JSONB com todos os dados do formulário de verificação do documento', null=True),
        ),
    ]
