# Generated by Django 5.2.6 on 2025-01-XX XX:XX

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0011_contrato_verifica_documento'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contabancariareu',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='contabancariareu',
            name='cliente',
        ),
        migrations.AlterModelOptions(
            name='contabancariareu',
            options={'ordering': ['banco_nome'], 'verbose_name': 'Banco do Réu', 'verbose_name_plural': 'Bancos dos Réus'},
        ),
        migrations.AlterUniqueTogether(
            name='contabancariareu',
            unique_together={('banco_nome', 'cnpj')},
        ),
    ]
