# Generated by Django 5.2.6 on 2025-01-XX XX:XX

import cadastro.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0012_remove_contabancariareu_cliente'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contabancariareu',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='contabancariareu',
            name='cnpj',
            field=models.CharField(max_length=14, unique=True, validators=[cadastro.validators.validate_cnpj]),
        ),
    ]
