# Generated by Django 5.2.6 on 2025-01-XX XX:XX

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0013_contabancariareu_cnpj_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='contabancariareu',
            name='descricao',
            field=models.TextField(blank=True),
        ),
    ]
