# Generated by Django 5.2.6 on 2026-03-15 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0016_descricaobanco_perf_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos_cadastro', to='cadastro.cliente'),
        ),
    ]
