# Generated by Django 5.2.6 on 2026-03-16 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0017_alter_contrato_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='beneficios',
            field=models.JSONField(blank=True, default=list, help_text='Array JSON de benefícios. Cada item: {numero: string, tipo: string}'),
        ),
    ]
