# Generated by Django 5.2.6 on 2026-04-01 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0018_cliente_beneficios'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='comprovante_nome_cliente',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AddField(
            model_name='cliente',
            name='comprovante_residencia',
            field=models.FileField(blank=True, upload_to='clientes/comprovantes/'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='condicao_cliente',
            field=models.CharField(blank=True, choices=[('alfabetizado', 'Alfabetizado'), ('analfabeto', 'Analfabeto'), ('incapaz', 'Incapaz'), ('crianca_adolescente', 'Criança/Adolescente')], default='alfabetizado', max_length=25),
        ),
        migrations.AddField(
            model_name='cliente',
            name='genero',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='cliente',
            name='nome_titular_numero',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='cliente',
            name='relacao_titular',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='cliente',
            name='relacao_titular_tipo',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='cliente',
            name='responsavel_imovel_cpf',
            field=models.CharField(blank=True, max_length=11),
        ),
        migrations.AddField(
            model_name='cliente',
            name='responsavel_imovel_doc',
            field=models.FileField(blank=True, upload_to='clientes/comprovantes/'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='responsavel_imovel_nome',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='cliente',
            name='responsavel_legal_cpf',
            field=models.CharField(blank=True, max_length=11),
        ),
        migrations.AddField(
            model_name='cliente',
            name='responsavel_legal_nome',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='cliente',
            name='rogado_cpf',
            field=models.CharField(blank=True, max_length=11),
        ),
        migrations.AddField(
            model_name='cliente',
            name='rogado_nome',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='cliente',
            name='telefone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='cliente',
            name='testemunha1_cpf',
            field=models.CharField(blank=True, max_length=11),
        ),
        migrations.AddField(
            model_name='cliente',
            name='testemunha1_nome',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='cliente',
            name='testemunha2_cpf',
            field=models.CharField(blank=True, max_length=11),
        ),
        migrations.AddField(
            model_name='cliente',
            name='testemunha2_nome',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='cliente',
            name='titular_contato',
            field=models.CharField(blank=True, max_length=3),
        ),
    ]
