# Generated by Django 5.2.6 on 2026-04-02 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0019_cliente_comprovante_nome_cliente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='isento_irpf',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='possui_imoveis',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='possui_moveis',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
