# Generated by Django 5.2.6 on 2026-04-07 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0020_cliente_isento_irpf_cliente_possui_imoveis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='documentos_pessoais',
            field=models.JSONField(blank=True, default=list, help_text='Array JSON de caminhos dos arquivos. Ex: ["clientes/docs/123_rg.jpg", ...]'),
        ),
    ]
