# Generated by Codex on 2026-04-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastro", "0021_add_documentos_pessoais"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="responsavel_legal_documentos",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="cliente",
            name="rogado_documentos",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="cliente",
            name="testemunha1_documentos",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="cliente",
            name="testemunha2_documentos",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
