# Generated by Django 5.2.6 on 2026-05-09 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0023_add_data_nascimento_to_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='telefones_extras',
            field=models.JSONField(blank=True, default=list, help_text='Telefones adicionais. Cada item: {numero, titular_contato, nome_titular_numero, relacao_titular_tipo, relacao_titular}'),
        ),
    ]
