# Generated by Django 5.2.6 on 2026-06-18 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0026_cliente_complemento'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='fotos_residencia',
            field=models.JSONField(blank=True, default=list, help_text='Array JSON de fotos da residência. Cada item: {path, name}'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
