# Generated by Django 5.2.6 on 2026-07-14 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0027_cliente_fotos_residencia_cliente_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='foto_cliente',
            field=models.JSONField(blank=True, default=None, help_text='Foto 3x4 do cliente: {path, name} ou None.', null=True),
        ),
    ]
