# Generated by Django 5.2.6 on 2026-08-18 01:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastro", "0028_cliente_foto_cliente"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="origem",
            field=models.CharField(
                choices=[
                    ("jurisdoc", "JurisDoc"),
                    ("app_cliente", "Pré-cadastro pelo app"),
                ],
                db_index=True,
                default="jurisdoc",
                max_length=15,
            ),
        ),
        migrations.CreateModel(
            name="ContaClienteApp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(db_index=True, max_length=254, unique=True),
                ),
                ("senha_hash", models.CharField(max_length=256)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("vinculada_a_ficha_existente", models.BooleanField(default=False)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("ultimo_login_em", models.DateTimeField(blank=True, null=True)),
                ("senha_alterada_em", models.DateTimeField(blank=True, null=True)),
                (
                    "cliente",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conta_app",
                        to="cadastro.cliente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Conta de cliente no app",
                "verbose_name_plural": "Contas de clientes no app",
                "ordering": ["-criado_em"],
            },
        ),
    ]
