# Generated by Django 5.2.6 on 2026-08-28 01:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastro", "0029_cliente_origem_contaclienteapp"),
    ]

    operations = [
        migrations.AddField(
            model_name="contaclienteapp",
            name="telefone",
            field=models.CharField(
                blank=True, db_index=True, max_length=20, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="contaclienteapp",
            name="vinculo_recusado",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="contaclienteapp",
            name="whatsapp_jid",
            field=models.CharField(blank=True, default="", max_length=60),
        ),
        migrations.AlterField(
            model_name="contaclienteapp",
            name="cliente",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="conta_app",
                to="cadastro.cliente",
            ),
        ),
        migrations.AlterField(
            model_name="contaclienteapp",
            name="email",
            field=models.EmailField(
                blank=True, db_index=True, max_length=254, null=True, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="contaclienteapp",
            name="senha_hash",
            field=models.CharField(blank=True, default="", max_length=256),
        ),
        migrations.CreateModel(
            name="CodigoAcessoCliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("telefone", models.CharField(db_index=True, max_length=20)),
                ("codigo_hash", models.CharField(max_length=256)),
                ("expira_em", models.DateTimeField(db_index=True)),
                ("tentativas", models.PositiveSmallIntegerField(default=0)),
                ("usado_em", models.DateTimeField(blank=True, null=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Código de acesso do cliente",
                "verbose_name_plural": "Códigos de acesso do cliente",
                "ordering": ["-criado_em"],
                "indexes": [
                    models.Index(
                        fields=["telefone", "-criado_em"],
                        name="cadastro_co_telefon_ff00c4_idx",
                    )
                ],
            },
        ),
    ]
