# Generated by Django 5.2.6 on 2026-09-03 23:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastro", "0030_contaclienteapp_telefone_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="contaclienteapp",
            name="indicado_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="clientes_app_indicados",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
