# Generated by Django 5.2.6 on 2026-09-04 16:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastro", "0031_contaclienteapp_indicado_por"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CadastroAppEnviado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cpf", models.CharField(db_index=True, max_length=11, unique=True)),
                ("telefone", models.CharField(blank=True, default="", max_length=20)),
                ("kit_id", models.IntegerField(blank=True, null=True)),
                ("notificacao_enviada", models.BooleanField(default=False)),
                ("enviado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="envios_app",
                        to="cadastro.cliente",
                    ),
                ),
                (
                    "indicado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cadastros_app_recebidos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Cadastro enviado pelo app",
                "verbose_name_plural": "Cadastros enviados pelo app",
                "ordering": ["-enviado_em"],
            },
        ),
    ]
