# Generated by Django 5.2.6 on 2026-04-02 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advogado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=200)),
                ('nacionalidade', models.CharField(default='brasileiro', max_length=60)),
                ('estado_civil', models.CharField(blank=True, max_length=20)),
                ('genero', models.CharField(choices=[('masculino', 'Masculino'), ('feminino', 'Feminino')], default='masculino', max_length=15)),
                ('is_socio', models.BooleanField(default=False, help_text='Sócio do escritório Azevedo Lima & Rebonatto')),
                ('escritorio_nome', models.CharField(blank=True, help_text='Nome do escritório individual (não-sócios)', max_length=200)),
                ('escritorio_cnpj', models.CharField(blank=True, help_text='CNPJ do escritório individual', max_length=20)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Advogado',
                'verbose_name_plural': 'Advogados',
                'ordering': ['-is_socio', 'nome_completo'],
            },
        ),
        migrations.CreateModel(
            name='OabUf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uf', models.CharField(max_length=2)),
                ('numero_oab', models.CharField(help_text='Ex: OAB/SC nº 36672', max_length=50)),
                ('unidade_apoio_nome', models.CharField(blank=True, help_text='Ex: Salvador', max_length=100)),
                ('unidade_apoio_endereco', models.TextField(blank=True, help_text='Endereço completo da unidade de apoio')),
                ('advogado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oabs', to='advogados.advogado')),
            ],
            options={
                'verbose_name': 'OAB por UF',
                'verbose_name_plural': 'OABs por UF',
                'ordering': ['uf'],
                'constraints': [models.UniqueConstraint(fields=('advogado', 'uf'), name='unique_advogado_uf')],
            },
        ),
    ]
