# Generated by Django 5.2.6 on 2026-04-28 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advogados', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advogado',
            name='escritorio_endereco',
            field=models.TextField(blank=True, help_text='Endereço completo do escritório individual'),
        ),
    ]
