# Generated by Django 5.2.6 on 2026-05-09 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advogados', '0003_advogado_tipos_acao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advogado',
            name='tipos_acao',
        ),
        migrations.AddField(
            model_name='oabuf',
            name='tipos_acao',
            field=models.JSONField(blank=True, default=list, help_text="Lista de tipos de ação (ex.: ['tarifa_bancaria', 'rmc']) ou ['todas']. Vazio = atua em todas."),
        ),
    ]
